### ISSUE TITLE
Print errors/warnings to STDERR/STDOUT

### ISSUE THREAD

**Issue by schelcj** [statgen/gotcloud#13]
Please print out any warnings/errors to STDOUT/STDERR in addition to any `.err` files.

**Comment by pjvandehaar** [comment]
See https://github.com/statgen/gotcloud/tree/peter-develop

**Comment by pjvandehaar** [comment]
Ah, got it, you're running gotcloud locally.  This issue will become much nastier with a cluster.

**Comment by pjvandehaar** [comment]
Is this solution working for you?

**Comment by schelcj** [comment]
Sorry, no, I haven't been able to switch to a dev branch on these runs.

**Comment by pjvandehaar** [comment]
I've merged that commit into master now, so whenever you update it should be ready.
