### ISSUE TITLE
Align test fails using gotcloud.1.17.5

### ISSUE THREAD

**Issue by mkolovic** [statgen/gotcloud#14]
I am configuring a Docker image to run GotCloud. Below are the steps taken while testing on a base image with all the requirements. 

```
$ wget https://github.com/statgen/gotcloud/archive/gotcloud.1.17.5.tar.gz
$ tar -xzf gotcloud.1.17.5.tar.gz -C /usr/local
$ cd /usr/local/gotcloud-gotcloud.1.17.5/src
$ make
$ cd /usr/local/gotcloud-gotcloud.1.17.5
$ scripts/check_requirements.sh
WARNING:  '/usr/local/gotcloud/bin' does not exist.  Continuing...
Good, you appear to have 'java' installed
Good, you appear to have 'make' installed
Good, you appear to have 'libssl' installed at the correct level
#============================================================
#   '/usr/local/gotcloud/test/umake' does not exist so you cannot test this install
#   Install it by doing 'sudo dpkg -i gotcloud-test_*.deb'
#============================================================
```
So it is not recognizing that gotcloud exists due to the specific version name, I realize that if I did a `git clone` this issue would not arise, or I could move `gotcloud-gotcloud.1.17.5` to `gotcloud`. Proceeding...

```
$ ./gotcloud align --test /root/testalign
Removing any previous results from: /root/testalign/aligntest
Running GOTCLOUD TEST, test log in: /root/testalign/aligntest.log
File sizes of 10 FASTQ input files referenced in '/usr/local/gotcloud-gotcloud.1.17.5/test/align/indexFile.txt' = 0.00 GB
Total temp space will be about 0.00 GB
Total space for BAM files will be about 0.00 GB
Be sure you have enough space to hold all this data
Created /root/testalign/aligntest/Makefiles/align_Sample1.Makefile
Created /root/testalign/aligntest/Makefiles/align_Sample2.Makefile
Created /root/testalign/aligntest/Makefiles/align_Sample3.Makefile
---------------------------------------------------------------------
Waiting while samples are processed...
Running make -f /root/testalign/aligntest/Makefiles/alignAll.Makefile > /root/testalign/aligntest/Makefiles/alignAll.Makefile.log 2> /root/testalign/aligntest/Makefiles/alignAll.Makefile.err...

Processing finished in 68 secs with no errors reported
Use of uninitialized value $ENV{"USER"} in concatenation (.) or string at /usr/local/gotcloud-gotcloud.1.17.5/scripts/runcluster.pl line 36.
Use of uninitialized value $ENV{"USER"} in concatenation (.) or string at /usr/local/gotcloud-gotcloud.1.17.5/scripts/runcluster.pl line 36.
Use of uninitialized value $ENV{"USER"} in concatenation (.) or string at /usr/local/gotcloud-gotcloud.1.17.5/scripts/runcluster.pl line 36.
Use of uninitialized value $ENV{"USER"} in concatenation (.) or string at /usr/local/gotcloud-gotcloud.1.17.5/scripts/runcluster.pl line 36.
Results from DIFF will be in /root/testalign/diff_logfiles_results.txt
Failed Makefile results validation. See mismatches in /root/testalign/diff_logfiles_results.txt
Comparison failed, test case FAILED.
CMD=/usr/local/gotcloud-gotcloud.1.17.5/scripts/diff_results_align.sh /root/testalign /usr/local/gotcloud-gotcloud.1.17.5/test/align/expected
```

So it seems as though the fastq files are not being recognized since it claims a total size of 0GB for them, even though the path to the files is correct. Please let me know if additional information is required, thanks.

**Comment by pjvandehaar** [comment]
1. I fixed your first error in [this commit](https://github.com/statgen/gotcloud/commit/de9069d528070c9f46e97e8d85241cd380a89230).  Sorry for not making a new release yet.

2. In your terminal, can you `echo $USER` and `env | grep USER`?  I don't understand why `$ENV{USER}` is `undef`.  That shouldn't be part of the error, but it indicates that strange things might be happening.

3. The test fastqs are smaller than 5MB, hence `0.00 GB`.  Thanks for pointing out the confusion that causes– I just updated it to print 6 decimal places.

Could you send me `/root/testalign/aligntest/Makefiles/alignAll.Makefile.err` and `/root/testalign/diff_logfiles_results.txt`?

**Comment by pjvandehaar** [comment]
Also: if you push that gotcloud image to a registry (eg dockerhub), I'd love a link to it.

**Comment by mkolovic** [comment]
1. Sorry for not digging around more! Does the error cause any other issues or only this confusion while testing? If there is no widespread impact I will continue using this release.

2. It's a Docker thing. You have to declare the environment variable within the Dockerfile like 
`ENV USER ubuntu` or similar. 

3. Makes sense, thanks.

4. I don't think this is necessary now since I seem to have it running once I configure a non-root user and set the `USER` environment variable. Here is the output from `gotcloud test` , which is set as the `ENTRYPOINT` or default command for the Docker image. I believe this indicates a successful installation.

```
$ docker run -it gotcloud:v1
... lots of make output...
using /usr/local/gotcloud-gotcloud.1.17.5/gotcloud
outputting to /tmp/gotcloud-tests-ubuntu-Gys
Wed Dec 9 19:09:25 UTC 2015 finished recabQC
Wed Dec 9 19:09:36 UTC 2015 finished bamQC
Wed Dec 9 19:10:25 UTC 2015 finished align
Wed Dec 9 19:10:48 UTC 2015 finished indel
Wed Dec 9 19:11:50 UTC 2015 finished snpcall
Wed Dec 9 19:12:25 UTC 2015 finished beagle
Wed Dec 9 19:13:17 UTC 2015 finished thunder
Wed Dec 9 19:13:20 UTC 2015 finished split4
Wed Dec 9 19:13:34 UTC 2015 finished beagle4
align         0
indel         0
bamQC         0
recabQC       0
snpcall       0
beagle        0
thunder       0
split4        0
beagle4       0
```

Thanks for the support, once I have a final version and the workflow figured out I will be pushing to Docker Hub so I will let you know.

**Comment by pjvandehaar** [comment]
That particular commit only affects the tests.  Since the last release we've fixed a few bugs, but I can just make a new release when your Dockerfile is ready.

Yes, those results for `gotcloud test` indicate success.  I've just made another change to make that more obvious.

If you want to use `gotcloud genomestrip`, you'll need to change a couple things.
