### ISSUE TITLE
`$val` is not initialized in one branch

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/gotcloud#8]
I'm getting the error

```
Use of uninitialized value $val in concatenation (.) or string at /tmp/ptr-seqshop/gotcloud/bin/align.pl line 998.
```

At https://github.com/statgen/gotcloud/tree/master/bin/align.pl#L992, should there be `$val = ''`?

**Comment by hyunminkang** [comment]
Seems right to me.

**Comment by mktrost** [comment]
Actually, I think that line 992 should have: "next;"
I don't believe anything should be output in the case of "RG" field.  If it inferred values, there shouldn't be an "RG" field - and there wasn't one output in the header.

**Comment by mktrost** [comment]
The code was also printing out an unnecessary tab on the header.  It should now be fixed in the master branch.
