### ISSUE TITLE
A GC-content graph is bounded (0,120)

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/gotcloud#9]
At https://github.com/statgen/gotcloud/blob/fe80263131766c65862cc3692bc9c5c174f98fe3/src/qplot/src/BamQC.cpp#L1065 and https://github.com/statgen/gotcloud/blob/fe80263131766c65862cc3692bc9c5c174f98fe3/src/qplot/src/BamQC.cpp#L1072, the graph of GC-content has x-axis limits of `(0,120)` .  Should it be `(0,100)`?

**Comment by hyunminkang** [comment]
This is fine. 100 (or 105?) might be better to avoid boundary cases.

**Comment by pjvandehaar** [comment]
I see, this keeps the legend from interfering with the graph.  Maybe it's fine then.
